version: '2'
services:
  mysql:
    container_name: 'mysql'
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kobe
      MYSQL_PASSWORD: denshi
    volumes:
      - db:/var/lib/mysql
    ports:
      - "33333:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_ROOT_PASSWORD=password
    links:
      - mysql
    ports:
      - 8000:80
    volumes:
      - /sessions
  php:
    build: ./php
    container_name: 'php'
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql
    ports:
      - 8080:80

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
volumes:
  db:
